### ISSUE TITLE
proposal: deprecate/archive this component

### ISSUE THREAD

**Issue by krancour** [brigadecore/brigade-acr-gateway#75]
Impetus:

The [CloudEvents Gateway](https://github.com/brigadecore/brigade-cloudevents-gateway) will go GA very soon and works very well with [Azure Event Grid](https://docs.microsoft.com/en-us/azure/event-grid/overview). This means the ability to receive events from just about any Azure resource -- including Azure Container Registries -- already exists.

I'm not keen to incur the ongoing maintenance burden of a gateway that works with _one_ Azure service, when we already have a component that works with _most_ Azure services.

Can we?

This component isn't GA get. So, yes.

Flip side:

If you configure webhooks _directly_ on an ACR, you have the option to provide an image name pattern that will send webhooks only for image names that match the pattern. If you're using Event Grid to wire events from your ACR into Brigade, you don't have that option.

Is it worth maintaining a whole separate gateway for the sake of that one option? I would argue that the answer is, "No... unless demand for it surfaces."

Ultimately I'm proposing that we archive this repository, but remain open-minded to the possibility of resuming work on it in the future.

cc @vdice for opinion.

**Comment by vdice** [comment]
I'm inclined to agree that it would be wise to focus the limited resources of the maintainers/contributors to the Brigade project towards the more broadly-useful CloudEvents Gateway for the reasons mentioned.  I'd say we move forward with archiving this component unless stakeholders/community members cry foul around the specific use case that would not be covered via Event Grid + CloudEvents gateway.

**Comment by krancour** [comment]
Thanks @vdice!
